### PR TITLE
fix(deepagents): use new StateSchema class

### LINKED ISSUE #122: fix: exclude files from subagent state updates / reopen pr #67
PR #74 does not fix this issue
After upgrading to v1.3.1 (which includes PR #74 ), the error still occurs, when running parallel subagents.

The Problem
PR #74 fixed schema object identity (WeakMap lookup issue).

This PR (#67 ) addresses a different issue: parallel subagents returning shared input files.

EXAMPLE

User uploads 4 files
│
▼
state.files = { A, B, C, D }
│
▼
Parent spawns 4 parallel subagents, each receives ALL 4 files
│
├─► Subagent 1: state.files = { A, B, C, D }
├─► Subagent 2: state.files = { A, B, C, D }
├─► Subagent 3: state.files = { A, B, C, D }
└─► Subagent 4: state.files = { A, B, C, D }
│
▼
Each subagent returns Command with ALL files
│
▼
4 Commands × 4 files = 16 updates to files channel in ONE step

Error: "LastValue can only receive one value per step"

The subagents return the same input files they received, causing duplicate updates.

@dqbd noted that EXCLUDED_STATE_KEYS is used for both input and output. If needed, we can split into two lists:

const EXCLUDED_FROM_SUBAGENT_INPUT = ["messages", "todos", "jumpTo"];
const EXCLUDED_FROM_SUBAGENT_OUTPUT = ["messages", "todos", "jumpTo", "files"];

This keeps input behavior unchanged while fixing the parallel return issue.

Can this PR be reopened?

### LINKED ISSUE #143: skillsMetadata causes concurrent update error when parallel subagents complete with skills middleware
## Description

When skills middleware is enabled (e.g. `skills: ['/.claude/skills/']`) and multiple subagents run in parallel, LangGraph throws a concurrent update error because `skillsMetadata` is not in `EXCLUDED_STATE_KEYS`.

## Error Message

```shell
Error: Invalid update for channel "skillsMetadata" with values [[],[],[],[]]: LastValue can only receive one value per step.
```

## Impact

We're looking to integrate `deepagents` into our production platform and this bug blocks us from using skills middleware with parallel subagents, which is a core part of our architecture. We have a working [fork](https://github.com/tverghonooks/deepagentsjs/tree/fix/exclude-skillsmetadata-from-subagent-state) with the fix, but would like to see this merged upstream so we can stay on the main release.

## Steps to Reproduce

1. Create an agent with skills middleware enabled:
```typescript
const agent = createDeepAgent({
  model: 'claude-sonnet-4-5-20250929',
  skills: ['/.claude/skills/'],
  // ... other config
});
```

2. Send a request that triggers multiple subagents in parallel (e.g., "research X, Y, Z, and W")

3. When 4 subagents complete simultaneously, each returns `skillsMetadata` in their state update

4. LangGraph fails because `skillsMetadata` uses implicit `LastValue` (no custom reducer)

## Root Cause

In `libs/deepagents/src/middleware/subagents.ts`, the `EXCLUDED_STATE_KEYS` array (line 33-38) includes `files` but not `skillsMetadata`:

```typescript
const EXCLUDED_STATE_KEYS = [
  "messages",
  "todos",
  "structuredResponse",
  "files",
  // "skillsMetadata" is missing
] as const;
```

When multiple subagents then return `skillsMetadata` simultaneously, LangGraph throws the error.

## Proposed Fix

Add `"skillsMetadata"` to `EXCLUDED_STATE_KEYS`:

```typescript
const EXCLUDED_STATE_KEYS = [
  "messages",
  "todos",
  "structuredResponse",
  "files",
  "skillsMetadata",  // Add this
] as const;
```

## Reproduction Steps / Example Code

```typescript
/**
 * Reproduction script for skillsMetadata concurrent update bug
 *
 * Requirements:
 *   Node.js >= 20.9.0
 *
 * Setup:
 *   npm install deepagents @langchain/anthropic tsx
 *   mkdir -p /tmp/skills/test-skill
 *   echo '---
 * name: test-skill
 * description: A test skill
 * ---
 * # Test Skill' > /tmp/skills/test-skill/SKILL.md
 *
 * Run:
 *   ANTHROPIC_API_KEY=your_key npx tsx repro-skillsmetadata-bug.ts
 *
 * Expected error (before fix):
 *   Invalid update for channel "skillsMetadata" with values [[...],[...],[...],[...]]:
 *   LastValue can only receive one value per step.
 */

import { createDeepAgent } from "deepagents";
import { HumanMessage } from "@langchain/core/messages";

async function reproduce() {
  console.log("=== skillsMetadata Concurrent Update Bug Reproduction ===\n");

  const agent = createDeepAgent({
    model: "claude-sonnet-4-5-20250929",
    skills: ["/tmp/skills/"],
    systemPrompt: `You coordinate research by delegating to subagents via the task tool.
IMPORTANT: When asked to get multiple answers, call the task tool multiple times IN PARALLEL (same message).
Subagents should just return a brief text answer - no file operations needed.`,
  });

  console.log("Sending request to trigger parallel subagents...\n");

  try {
    const result = await agent.invoke({
      messages: [
        new HumanMessage(
          "Use the task tool to spawn 4 subagents IN PARALLEL (all 4 task calls in one message). " +
          "Each subagent should answer ONE of these questions with a single sentence:\n" +
          "1) What is 2+2?\n" +
          "2) What is the capital of France?\n" +
          "3) What color is the sky?\n" +
          "4) How many days in a week?\n\n" +
          "Call task 4 times simultaneously. Subagents should just return the answer, no tools needed."
        ),
      ],
    });

    const lastMsg = result.messages[result.messages.length - 1];
    console.log("Result:", String(lastMsg?.content).slice(0, 500));
  } catch (error: any) {
    if (error.message?.includes("LastValue") && error.message?.includes("skillsMetadata")) {
      console.log("BUG REPRODUCED!\n");
      console.log("Error:", error.message);
    } else {
      console.log("Error:", error.message);
    }
  }
}

reproduce().catch(console.error);
```

## Environment / System Info

- deepagents version: 1.6.0
- Node.js: 20.x, 22.x
- OS: macOS

### LINKED ISSUE #144: InvalidUpdateError: LastValue can only receive one value per step when writing multiple files in parallel
When the agent attempts to write multiple files in a single step (e.g., saving both user_prompt.txt and context.txt simultaneously), the graph throws an InvalidUpdateError because the files channel is configured with a LastValue reducer.|

InvalidUpdateError: Invalid update for channel "files" with values [
  {"/user_prompt.txt": {...}},
  {"/context.txt": {...}}
]: LastValue can only receive one value per step.

Troubleshooting URL: https://docs.langchain.com/oss/javascript/langgraph/INVALID_CONCURRENT_GRAPH_UPDATE/

at Object._applyWrites (.../node_modules/@langchain/langgraph/src/pregel/algo.ts:336:32)
at PregelLoop.tick (.../node_modules/@langchain/langgraph/src/pregel/loop.ts:747:30)
at CompiledStateGraph._runLoop (.../node_modules/@langchain/langgraph/src/pregel/index.ts:2257:20)

The agent should be able to write multiple files in a single step without errors. This is a common use case when the agent needs to save related context files together for efficiency

### PR DESCRIPTION
**Pull request by christian-bromann**
This PR fixes a LangGraph `LastValue` channel error that occurs when parallel subagents update state simultaneously. The fix migrates state schemas to use LangGraph's new `StateSchema` class with `ReducedValue` to enable proper concurrent state updates.

**Problem:** When skills or filesystem middleware is enabled and multiple subagents run in parallel, each subagent returns state updates (e.g., `skillsMetadata`, `files`). Since these fields used implicit `LastValue` semantics (no custom reducer), LangGraph fails with:

```
Invalid update for channel "skillsMetadata" with values [[...],[...],[...]]:
LastValue can only receive one value per step.
```

**Solution:** Use `StateSchema` with `ReducedValue` and custom reducers that properly merge concurrent updates:

- `skillsMetadataReducer`: Merges skill arrays, deduplicating by name (later values override earlier)
- `fileDataReducer`: Merges file records with support for deletions (null values remove files)

closes #142
fixes #143
fixes #144
fixes #122

### CODE REVIEW

File: libs/deepagents/src/middleware/fs.ts [hunk 1]
```diff
@@ -166,17 +198,17 @@ function fileDataReducer(
...
-const FilesystemStateSchema = z.object({
-  files: z
-    .record(z.string(), FileDataSchema)
-    .default({})
-    .meta({
-      reducer: {
-        fn: fileDataReducer,
-        schema: z.record(z.string(), FileDataSchema.nullable()),
-      },
-    }),
```
Comment (hntrl) [inline libs/deepagents/src/middleware/fs.ts:179]: FWIW I don't think that the issue is with how reducers are composed with zod objects (though this way of doing things is pretty flaky). `.meta` pins values to zod's default reducer, not the one that langgraph targets.

Regardless, we should use StateSchema 🙂
